# Generated by Django 4.2.7 on 2026-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_appuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='college',
            field=models.CharField(default='mrce', max_length=150),
            preserve_default=False,
        ),
    ]
